#!/bin/sh

PORT="http_port $PORT"
DOMIAN="visible_hostname $DOMIAN"
ONLYV4="dns_v4_first $ONLYV4"
WORDS="auth_param basic realm $WORDS"
sed -e '2c/$PORT' /etc/squid/squid.conf
sed -e '3c/$DOMIAN' /etc/squid/squid.conf
sed -e '4c/$ONLYV4' /etc/squid/squid.conf
sed -e '55c/$WORDS' /etc/squid/squid.conf

set -e
htpasswd -bc /usr/etc/passwd "${SQUID_USERNAME}" "${SQUID_PASSWORD}"
CHOWN=$(/usr/bin/which chown)
SQUID=$(/usr/bin/which squid)
"$CHOWN" -R squid:squid /var/cache/squid
"$CHOWN" -R squid:squid /var/log/squid
squid -N $*
exec tail -F /var/log/squid/cache.log
